name: Build Database Update
on:
  push:
    paths:
    - '.github/workflows/*'
  workflow_dispatch:
  schedule:
    - cron:  '15 8 * * *'

jobs:
  build_and_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        sudo apt-get install ipcalc jq
    - name: Downloading SFS IP list
      run: |
        curl https://ip-ranges.amazonaws.com/ip-ranges.json | jq '.prefixes[] | select(.service=="ROUTE53_HEALTHCHECKS") | .ip_prefix' -r > /tmp/route53.lsv
    - name: Build list
      run: |
        perl ./helpers/cleanup.pl /tmp/route53.lsv > ipv4.txt
    - name: Push Output of ipv4.txt
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        source_file: 'ipv4.txt'
        destination_repo: '${{ github.repository }}'
        destination_folder: '/'
        user_email: 'automated@x4b.net'
        user_name: 'listbuilder'
        destination_branch: "main"

